### ISSUE TITLE
cannot find @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by UziTech** [atom-ide-community/atom-ide-template#21]
![image](https://user-images.githubusercontent.com/97994/90706966-0d865f00-e25c-11ea-9b35-f34cf8a76709.png)

only happens when I use `pnpm i` to install the dependencies `npm i` makes it work. I'm not sure if this is an issue in pnpm or eslint-config-atomic

**Comment by UziTech** [comment]
strangely `npm run lint` works so this might be an error in `linter-eslint`

**Comment by UziTech** [comment]
Now I'm really confused how `npm run lint` works since it doesn't look like `@typescript-eslint/eslint-plugin` is installed by `pnpm`

![image](https://user-images.githubusercontent.com/97994/90708577-c601d200-e25f-11ea-8aba-1d0237cb87ac.png)

but it is when I use `npm i`

![image](https://user-images.githubusercontent.com/97994/90710314-bc7a6900-e263-11ea-8dea-9d7ce6f453fe.png)

**Comment by aminya** [comment]
This should fix it: https://github.com/atom-ide-community/eslint-config-atomic/commit/6a4f7010d9b092545cea7601285a4d22efc29466

Based on: https://pnpm.js.org/en/npmrc#shamefully-hoist

**Comment by aminya** [comment]
The fix is available in eslint-config-atomic 1.4.0

**Comment by aminya** [comment]
It seems linter-eslint still does not find the plugins.

**Comment by aminya** [comment]
Opened an issue in https://github.com/pnpm/pnpm/issues/2781

**Comment by aminya** [comment]
I fixed this temporarily by adding the `.npmrc` to this package instead. Get that file and run `pnpm install` again. I will track the upstream pnpm issue.
